config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'movies#index'

  resources :movies
  resources :directors, only: [:index, :show]

  get 'results', to: 'searches#results'
  post 'add/:imdb_id', to: 'movies#add', as: :add_to_database

  # Replaced these with "resources :movies"
  # get 'movies', to: 'movies#index', as: :movies
  # get 'movies/:id', to: 'movies#show', as: :movie
  # get 'movies/new', to: 'movies#new', as: :new_movie
  # get 'movies/:id/edit', to: 'movies#edit', as: :edit_movie
  # post 'movies', to: 'movies#create'
  # patch 'movies/:id', to: 'movies#update'
  # delete 'movies/:id', to: 'movies#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movie_directors
  has_many :movies, through: :movie_directors
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord

  # Associations
  belongs_to :rating

  has_many :movie_genres
  has_many :movie_directors
  has_many :user_movies
  has_many :genres, through: :movie_genres
  has_many :directors, through: :movie_directors
  has_many :users, through: :user_movies

  # Creates getter/setters
  # attr_accessor :imdb_id # No longer needed now that it's a column in the db

  validates :imdb_id, uniqueness: true
  validates :title, presence: true

  def self.add(imdb_id)
    # Return the movie if it already exists
    existing_movie = Movie.find_by(imdb_id: imdb_id)
    return existing_movie if existing_movie

    response = HTTParty.get("#{OMDB_API_URL}/?i=#{imdb_id}")
    data = JSON.parse(response.body)

    # Check if the rating already exists in the db,
    # if not, create it
    rating = Rating.where(name: data['Rated']).first_or_create


    # Initialize a new movie with data from OMDB
    released_date = data['Released'] == 'N/A' ? nil : DateTime.parse(data['Released'])

    new_movie = Movie.new(imdb_id: imdb_id,
                          title: data['Title'],
                          poster: data['Poster'],
                          date: released_date,
                          length: data['Runtime'].to_i,
                          rating: rating,
                          plot: data['Plot'],
                          metascore: data['Metascore'].to_i,
                          imdb_rating: data['imdbRating'].to_f,
                          imdb_votes: data['imdbVotes'].to_i
    )

    # Split up the genres and add them to the movie
    data['Genre'].split(', ').each do |genre_name|
      genre = Genre.where(name: genre_name).first_or_create
      new_movie.genres << genre
    end

    data['Director'].split(', ').each do |director_name|
      director = Director.where(name: director_name).first_or_create
      new_movie.directors << director
    end

    new_movie.save
    new_movie
  end

  def display_name
    "#{title} (#{rating.name})"
  end

  def genre_names
    genres.collect(&:name).join(', ')
  end

  def imdb_results
    "#{imdb_rating} (#{imdb_votes} votes)"
  end

  #def director_names
  #  names = 'Director'
  #  if directors.size > 1
  #    names = names + 's'
  #  end
  #  names + ': ' + directors.collect(&:name).join(', ')
  #end
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/rating.rb
class Rating < ApplicationRecord

  has_many :movies

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_movies
  has_many :movies, through: :user_movies
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = @director.movies
  end

  def search
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = if params[:query]
                current_user.movies.where("UPPER(title) LIKE UPPER(?)", "%#{params[:query]}%")
              else
                current_user.movies
              end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  # Javascript only
  def add
    movie = Movie.add(params[:imdb_id])

    if movie.persisted? && current_user.movies << movie
      head :ok
    else
      head :internal_server_error
    end

  end

  private

  def movie_params
    params.require(:movie).permit(:title, :date, :length)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:results]

  def results
    query = params[:query]
    response = HTTParty.get("http://www.omdbapi.com/?s=#{query}&type=movie")
    data = JSON.parse(response.body)

    @movies = []
    data['Search'].each do |movie_result|
      new_movie = Movie.new(title: movie_result['Title'],
                           poster: movie_result['Poster'],
                           date: Date.new(movie_result['Year'].to_i))

      new_movie.imdb_id = movie_result['imdbID']

      @movies << new_movie
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
  def poster_for_director(director)
    image_path = director.poster.present? ? director.poster : 'missing_director.png'
    image_tag image_path
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def poster_for(movie)
    image_path = movie.poster.present? ? movie.poster : 'missing_poster.png'
    image_tag image_path
  end

  def imdb_rating_for(movie)
    twice_rating_rounded = (movie.imdb_rating * 2).round
    num_halves = twice_rating_rounded % 2 # Get the number of halves, 0 or 1

    content_tag :span, class: 'imdb_rating' do
      results = "(#{movie.imdb_rating}) "
      # Full stars
      movie.imdb_rating.round.times do
        results << fa_icon('star')
      end

      # Half star (if any)
      if num_halves > 0
        results << fa_icon('star-half-o')
      end

      # Empty stars
      (10 - (twice_rating_rounded / 2)).times do
        results << fa_icon('star-o')
      end

      results.html_safe
    end
  end
end

app/views/directors/index.html.haml
.row
  - @directors.each do |director|
    .director.col-md-2
      .poster
        = link_to poster_for_director(director), director
      .details
        = link_to director.name, director

app/views/directors/show.html.haml
.row
  .col-12.col-md-3
    .director
      .poster
        = poster_for_director(@director)

      .title
        = @director.name

  .col-12.col-md-9
    - @movies.each do |movie|
      .row.movie
        .col-md-3
          .m-2
            = link_to poster_for(movie), movie
        .col-md-9
          .m-2
            .title= link_to movie.display_name, movie
            = movie.plot

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MovieTracker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# Header
    %nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
      %button.navbar-toggler.navbar-toggler-right
        %span.navbar-toggler-icon
      = link_to 'MovieTracker', root_path, class: 'navbar-brand'

      .collapse.navbar-collapse#navbarSupportedContent
        %ul.navbar-nav.mr-auto
          - if signed_in?
            %li.nav-item
              = link_to 'My Movies', movies_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Directors', directors_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'

        = form_tag '/results', method: :get, class: 'form-inline my-2 my-lg-0' do
          = text_field_tag :query, '', placeholder: 'Search for a movie', class: 'form-control mr-sm-2'
          = submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

    -# Body
    .container

      - if notice
        = notice
      - if alert
        = alert

      = yield

    -# Footer

app/views/movies/_form.html.haml
= form_for @movie do |f|

  = f.label :title
  = f.text_field :title

  = f.label :date, 'Release Date'
  = f.date_field :date

  = f.label :length
  = f.number_field :length

  = f.submit

app/views/movies/_movie.html.haml
.col-12.col-sm-6.col-md-4.col-lg-3.col-xl-2
  = link_to movie do
    .movie
      .poster
        = poster_for(movie)
      .details
        .title
          = movie.display_name
          = movie.date.try(:year)

app/views/movies/edit.html.haml
%h1 Edit Movie

= render 'form'

app/views/movies/index.html.haml
.row
  .mx-auto
    .col
      = form_tag movies_path, method: :get, class: 'form-inline mb-5' do
        = text_field_tag :query, '', placeholder: 'Search for a movie', class: 'form-control form-control-lg mr-2'
        = submit_tag 'Search', class: 'btn btn-primary btn-lg'

.row
  = render @movies

app/views/movies/new.html.haml
%h1 New Movie

= render 'form'

app/views/movies/show.html.haml
.row
  .col-12.col-sm-6.col-md-4.col-lg-2
    .movie
      .poster
        = poster_for(@movie)

  .col-12.col-sm-6.col-md-8.col-lg-10
    .title
      = @movie.display_name
    .details
      .genres
        = @movie.genre_names
      .metascore
        Metascore:
        = @movie.metascore
      .imdb_rating
        IMDB Rating:
        = imdb_rating_for(@movie)
      .director
        Director(s):
        -@movie.directors.each do |d|
          .name
            = link_to d.name, "directors/#{d.id}"


.row.moviePlot
  .col-12
    = @movie.plot

app/views/searches/results.html.haml
.row
  - @movies.each do |movie|
    .col-md-4
      .movie.movie_searches
        .poster= image_tag movie.poster
        .details
          .title
            = movie.title
            = movie.date.try(:year)
          .buttons
            -# Generally would be a POST request, but the Javascript intercepts it.
            = link_to add_to_database_path(movie.imdb_id), class: 'btn btn-primary add_movie' do
              = image_tag 'loading.gif', class: 'loading'
              .glyph_add= fa_icon('plus')
              .glyph_confirmed= fa_icon('check')
              .glyph_error= fa_icon('exclamation')